export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const RETRIEVE_PRODUCTS = 'RETRIEVE_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SEARCH_PRODUCT_BYNAME = 'SEARCH_PRODUCT_BYNAME';

export const RETRIEVE_PRODUCT = 'RETRIEVE_PRODUCT';
export const ADDING_TO_CART = 'ADDING_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SORT_PRODUCT = 'SORT_PRODUCT';
