# Generated by Django 3.2.9 on 2021-11-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
    ]
