# Generated by Django 3.2.9 on 2021-11-25 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211123_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
